### ISSUE TITLE
How are you dealing with Clojure 1.7's clojure.core/update?

### ISSUE THREAD

**Issue by robert-stuttaford** [Prismatic/plumbing#76]
We require plumbing in a uniform manner:

```clojure
(ns ...
  (:require [plumbing.core :refer :all]))
```

Using Clojure 1.7-alpha4, we now get a ton of warnings like this:

`WARNING: update already refers to: #'clojure.core/update in namespace: one.of.our.namespaces, being replaced by: #'plumbing.core/update`.

Do you anticipate altering plumbing to rename your `update`, or do we need to explicitly exclude clojure's update like this?

```clojure
(ns ...
  (:refer-clojure :exclude [update])
  (:require [plumbing.core :refer :all]))
```

FWIW, we don't actually use `plumbing.core/update`. I just want the warnings to go away :-)

**Comment by w01fe** [comment]
Fixed by #78 (thanks again!)
