### ISSUE TITLE
java equals/hash warnings

### ISSUE THREAD

**Issue by gfredericks** [Prismatic/plumbing#80]
Should `distinct-by` have the same warnings about java equals/hash that `frequencies-fast` and `distinct-fast` do?

**Comment by w01fe** [comment]
Yes, I suppose it should -- good catch.  Or it could just be written in a more efficient Clojurey way and share that between clj and cljs -- basically the cljs implementation with a transient set.

**Comment by gfredericks** [comment]
I think I'd prefer the latter option, since otherwise there wouldn't be a well-behaved `distinct-by` available; shall I make a PR?

**Comment by w01fe** [comment]
Yes, that would be very welcome -- thanks!

**Comment by w01fe** [comment]
Thanks again for the fix!
