### ISSUE TITLE
update isn't excluded

### ISSUE THREAD

**Issue by MichaelBlume** [Prismatic/plumbing#93]
I don't know why, but plumbing exports update even though I'm using Clojure 1.7

WARNING: update already refers to: #'clojure.core/update in namespace: plumbing.core, being replaced by: #'plumbing.core/update
WARNING: update already refers to: #'clojure.core/update in namespace: compojure.api.meta, being replaced by: #'plumbing.core/update
WARNING: update already refers to: #'clojure.core/update in namespace: ring.swagger.core, being replaced by: #'plumbing.core/update

lein deps :tree indicates I'm using plumbing 0.4.1

**Comment by dparis** [comment]
I'm seeing something similar: `WARNING: update already refers to: #'clojure.core/update in namespace: plumbing.graph.positional, being replaced by: #'plumbing.core/update`

It would be great to get this sorted out, my team is giving an internal demo of a clojure project next week and it would great to not have to start off the demo with an explanation that the dire-looking WARNING text is nothing to be concerned about. :smile:

**Comment by MichaelBlume** [comment]
Yay, thanks =)

**Comment by w01fe** [comment]
you're welcome, thanks for the report :).  just released 0.4.2 with this change.

**Comment by jenanwise** [comment]
FYI this is still an issue in 0.4.2. The `:refer-clojure :exclude` didn't make into that release.

**Comment by w01fe** [comment]
Oops, sorry about that -- forgot to pull before I released.   Just released 0.4.3 with this change.

**Comment by jenanwise** [comment]
:thumbsup: thanks!
