### ISSUE TITLE
Trying to clone and install fails

### ISSUE THREAD

**Issue by tangrammer** [Prismatic/plumbing#99]
Hi Prismatic guys!
I'm trying to make minor changes https://github.com/Prismatic/plumbing/issues/74 to your awesome lib

I've just forked and cloned the repo
but when I try 
`lein install`
then I get 
```
Reloading Clojure file "/plumbing/fnk/impl.clj" failed.
java.io.FileNotFoundException: Could not locate schema/core__init.class or schema/core.clj on classpath: 
              RT.java:443 clojure.lang.RT.load
              RT.java:411 clojure.lang.RT.load
            core.clj:5530 clojure.core/load[fn]
            core.clj:5529 clojure.core/load
          RestFn.java:408 clojure.lang.RestFn.invoke
            core.clj:5336 clojure.core/load-one
            core.clj:5375 clojure.core/load-lib[fn]
            core.clj:5374 clojure.core/load-lib
          RestFn.java:142 clojure.lang.RestFn.applyTo
             core.clj:619 clojure.core/apply
            core.clj:5413 clojure.core/load-libs
          RestFn.java:137 clojure.lang.RestFn.applyTo
             core.clj:619 clojure.core/apply
            core.clj:5496 clojure.core/require
          RestFn.java:482 clojure.lang.RestFn.invoke
               impl.clj:1 plumbing.fnk.impl/eval2307[fn]
               impl.clj:1 plumbing.fnk.impl/eval2307
       Compiler.java:6619 clojure.lang.Compiler.eval
       Compiler.java:6608 clojure.lang.Compiler.eval

....

```

Thanks!
Juan

**Comment by loganlinn** [comment]
Looks like the `cljx` task doesn't get hooked into `install` task. Try `lein cljx once` before your `lein install`

**Comment by tangrammer** [comment]
Thanks @loganlinn ! but... same error with that preinstall command
```
WARNING: Use of undeclared Var plumbing.fnk.schema/o2 at line 241 /Users/tangrammer/git/tangrammer/plumbing/target/generated/src/cljs/plumbing/fnk/schema.cljs
Compiling "target/main.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:target/generated/src/cljs/plumbing/core.cljs
               core.clj:4327 clojure.core/ex-info
            compiler.clj:891 cljs.compiler/compile-file
            compiler.clj:953 cljs.compiler/compile-root
             closure.clj:398 cljs.closure/compile-dir
             closure.clj:430 cljs.closure/eval1958[fn]
             closure.clj:299 cljs.closure/eval1885[fn]
             closure.clj:444 cljs.closure/eval1945[fn]
...
```

**Comment by w01fe** [comment]
Thanks for the report.  I've tried to replicate with a clean clone, the latest lein, and empty profiles.clj and it still works for me.  Can you provide the output of `lein --version`?  Do you have anything in your `~/.lein/profiles.clj` that might be causing issues?

**Comment by tangrammer** [comment]
Hi @w01fe ! 
The problem keeps the same with your new steps proposed

My profiles.clj don't have any data inside, just the `{}`

my lein version:
`Leiningen 2.5.1 on Java 1.8.0_31 Java HotSpot(TM) 64-Bit Server VM`

and here the full terminal output 
https://gist.github.com/tangrammer/339da8e1842cc69b7bf1

Thanks in advance!
Juan

**Comment by w01fe** [comment]
Hi Juan,

I just tried and can reproduce with your fork of master and the latest
leiningen.   But, it looks like you're 107 commits behind our master -- do
you mean to be on this old version?  Does it work for you with the latest
version of plumbing?

Thanks,
Jason

**Comment by tangrammer** [comment]
Hi Jason and sorry about my mistake, I expected that if you click on github fork and you have a current fork you get any message noting that 

Thanks for your help!

**Comment by w01fe** [comment]
No problem, glad we got this resolved.
